# -*- coding: utf-8 -*-
{
    "name": "Mgs Billing",
    "summary": """
        """,
    "description": """
        
    """,
    "author": "Meisour GS",
    "website": "https://www.meisour.com",
    "category": "Billing",
    "version": "0.1",
    "depends": ["base", "product", "account", "mail", "mgs_partner_balance"],
    "data": [
        "security/security_groups.xml",
        "security/ir.model.access.csv",
        "views/partner.xml",
        # 'views/owner.xml',
        "reports/collection_report.xml",
        "reports/billing_sale.xml",
        "reports/all_reveivables.xml",
        "reports/billed_percentage.xml",
        "reports/billing_receipt.xml",
        "reports/connect_disconnect.xml",
        "reports/meter_cubic_sold.xml",
        "reports/get_monthes_due.xml",
        "reports/property_log_rep.xml",
        "wizards/all_receivables_wiz.xml",
        "wizards/billed_percentage_wiz.xml",
        "wizards/connect_disconnect_wiz.xml",
        "wizards/collection_report_wiz.xml",
        "wizards/meter_cubic_sold_wiz.xml",
        "wizards/apply_extra_charge_wiz.xml",
        "wizards/con_desc_comment.xml",
        "wizards/get_monthes_due.xml",
        "wizards/property_log_wiz.xml",
        "views/zone.xml",
        "views/property.xml",
        "views/guarantor.xml",
        "views/meters.xml",
        "views/reset_meter.xml",
        "data/seq.xml",
        "views/tenancy.xml",
        "views/product.xml",
        "views/reading.xml",
        "views/meter_reading.xml",
        "views/document_type.xml",
        "views/res_config.xml",
        "views/mgs_billing_menu.xml",
    ],
    "license": "LGPL-3",
    "installable": True,
    "application": True,
}
