# -*- coding: utf-8 -*-
{
    "name": "Billing",
    "summary": """Meisour Custome Billing Module""",
    
    "description": """
        This module transforms Odoo into a powerful utility billing platform,
        designed for companies that bill customers based on their consumption of services.
        By integrating seamlessly with Odoo's existing accounting and CRM applications, 
        it provides a comprehensive solution for meter management, 
        automated billing, and customer service.
    """,
    
    "author": "Meisour GS",
    "website": "https://www.meisour.com",
    "category": "Billing",
    "version": "18.0",
    "depends": ["base", "mail", "product", "account", "crm"],
    
    
    "data": [
        "data/seq.xml",
        "security/ir.model.access.csv",
        "security/security_groups.xml",
        "views/balance_transfer.xml",
        "views/billing_account.xml",
        "views/billing_customer.xml",
        "views/collector.xml",
        "views/crm.xml",
        "views/document_type.xml",
        "views/guarantor.xml",
        "views/meter_reading.xml",
        "views/meters.xml",
        "views/mgs_billing_menu.xml",
        "views/product.xml",
        "views/property_type.xml",
        "views/property.xml",
        "views/reading.xml",
        "views/res_config.xml",
        "views/reset_meter.xml",
        "views/zone.xml",
        "reports/all_receivables_pdf.xml",
        "reports/all_reveivables.xml",
        "reports/billed_percentage.xml",
        "reports/billing_receipt.xml",
        "reports/billing_sale.xml",
        "reports/calling_report.xml",
        "reports/collection_report_pdf.xml",
        "reports/collection_report.xml",
        "reports/connect_disconnect.xml",
        "reports/get_monthes_due.xml",
        "reports/meter_cubic_sold.xml",
        "reports/payment_collection.xml",
        "reports/property_log_rep.xml",
        "wizards/all_receivables_wiz.xml",
        "wizards/apply_extra_charge_wiz.xml",
        "wizards/billed_percentage_wiz.xml",
        "wizards/calling_report.xml",
        "wizards/collection_report_wiz.xml",
        "wizards/con_desc_comment.xml",
        "wizards/connect_disconnect_wiz.xml",
        "wizards/create_billing_customer.xml",
        "wizards/get_monthes_due.xml",
        "wizards/meter_cubic_sold_wiz.xml",
        "wizards/payment_collection_wizard.xml",
        "wizards/property_log_wiz.xml"
    ],
    "license": "LGPL-3",
    "installable": True,
    "application": True,
}
